$axure.loadCurrentPage({
  "url":"图文详情.html",
  "generationDate":new Date(1488439924331.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"71c709b18b804bb4a49fbcb54bdf2ede",
    "type":"Axure:Page",
    "name":"图文详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0b15e5106f294c3ca72c2b559be24355",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7542e99a108c488c89ef787a7aaef9b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/图文详情/u0.jpg"}},
{
          "id":"d32b3c2f99b2409a8591365c359b9a74",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":333,
              "y":14},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "0b15e5106f294c3ca72c2b559be24355":{
      "scriptId":"u0"},
    "7542e99a108c488c89ef787a7aaef9b7":{
      "scriptId":"u1"},
    "d32b3c2f99b2409a8591365c359b9a74":{
      "scriptId":"u2"}}});