$axure.loadCurrentPage({
  "url":"优惠速递.html",
  "generationDate":new Date(1488438989661.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"11281ff4c8e14fc9bb0429b5200e410b",
    "type":"Axure:Page",
    "name":"优惠速递",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4c4596ab788541db90bfb49175423d80",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95190799e6ff464b81c6014b110e2fcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/优惠速递/u0.jpg"}},
{
          "id":"e3a370351b4145a283fb1008db2f999e",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":410},
            "size":{
              "width":170,
              "height":250}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7642e804e91343d093f9fdf79dc335e0",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":150},
            "size":{
              "width":170,
              "height":250}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7c78bedce3734f9abc6a136c12947c88",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":149},
            "size":{
              "width":170,
              "height":250}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"c58bbe3f44b548ae912df5a4e1e3d0df",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":405},
            "size":{
              "width":170,
              "height":250}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a6477cfda6d6499ea0c815351ce1bf2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF8E01C},
            "location":{
              "x":0,
              "y":660},
            "size":{
              "width":375,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06031c060592406d8fcb6c34c2d8f9ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF8E01C},
                "location":{
                  "x":0,
                  "y":660},
                "size":{
                  "width":375,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u17.png"}},
{
          "id":"57f0f6955e1e4dee939a7494f9335834",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":661},
            "size":{
              "width":27,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"568777e6e7e843759cee02de565ed2bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":23,
                  "y":661},
                "size":{
                  "width":27,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u19.png"}},
{
          "id":"5c571bc4a5064a2581a7ba973947587b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":661},
            "size":{
              "width":27,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"028bf9e61cd44b948b3d89b17c6916b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":661},
                "size":{
                  "width":27,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u21.png"}},
{
          "id":"203a920362414e0797001dbccafed1e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":661},
            "size":{
              "width":27,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b13aa90f6de34e9b96412e653e4ecc1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":253,
                  "y":661},
                "size":{
                  "width":27,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u23.png"}},
{
          "id":"914283b283574c95a054c577ea67cd96",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":662},
            "size":{
              "width":27,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a266246018b34b55bc0701cfb422f155",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":662},
                "size":{
                  "width":27,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u25.png"}},
{
          "id":"b7fea5abbcf64d058e7cf03af4c2811f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":663},
            "size":{
              "width":27,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7b589b126a44674b0e218ef7068304f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":663},
                "size":{
                  "width":27,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u27.png"}},
{
          "id":"7e6eb160a6f449e4b16223c102d2fc27",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":12.5,
              "y":661},
            "size":{
              "width":48,
              "height":44}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open index in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"732caeb8cb3749aba876217364647ca7",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":663},
            "size":{
              "width":48,
              "height":44}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 分类 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"分类.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"6bdb3df42ea248a99448387828b40d8e",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":242,
              "y":661},
            "size":{
              "width":48,
              "height":44}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 购物车 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b94426f9fa8f421aa8ec3addad50f8d5",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":662},
            "size":{
              "width":48,
              "height":44}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 登录 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "4c4596ab788541db90bfb49175423d80":{
      "scriptId":"u0"},
    "95190799e6ff464b81c6014b110e2fcd":{
      "scriptId":"u1"},
    "e3a370351b4145a283fb1008db2f999e":{
      "scriptId":"u2"},
    "7642e804e91343d093f9fdf79dc335e0":{
      "scriptId":"u3"},
    "7c78bedce3734f9abc6a136c12947c88":{
      "scriptId":"u4"},
    "c58bbe3f44b548ae912df5a4e1e3d0df":{
      "scriptId":"u5"},
    "a6477cfda6d6499ea0c815351ce1bf2d":{
      "scriptId":"u6"},
    "06031c060592406d8fcb6c34c2d8f9ef":{
      "scriptId":"u7"},
    "57f0f6955e1e4dee939a7494f9335834":{
      "scriptId":"u8"},
    "568777e6e7e843759cee02de565ed2bb":{
      "scriptId":"u9"},
    "5c571bc4a5064a2581a7ba973947587b":{
      "scriptId":"u10"},
    "028bf9e61cd44b948b3d89b17c6916b3":{
      "scriptId":"u11"},
    "203a920362414e0797001dbccafed1e6":{
      "scriptId":"u12"},
    "b13aa90f6de34e9b96412e653e4ecc1f":{
      "scriptId":"u13"},
    "914283b283574c95a054c577ea67cd96":{
      "scriptId":"u14"},
    "a266246018b34b55bc0701cfb422f155":{
      "scriptId":"u15"},
    "b7fea5abbcf64d058e7cf03af4c2811f":{
      "scriptId":"u16"},
    "a7b589b126a44674b0e218ef7068304f":{
      "scriptId":"u17"},
    "7e6eb160a6f449e4b16223c102d2fc27":{
      "scriptId":"u18"},
    "732caeb8cb3749aba876217364647ca7":{
      "scriptId":"u19"},
    "6bdb3df42ea248a99448387828b40d8e":{
      "scriptId":"u20"},
    "b94426f9fa8f421aa8ec3addad50f8d5":{
      "scriptId":"u21"}}});