$axure.loadCurrentPage({
  "url":"搜帘宝.html",
  "generationDate":new Date(1488187021059.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3287c8429f5041e6b2299f2447dbe74e",
    "type":"Axure:Page",
    "name":"搜帘宝",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4865bcdee7bf42caad21ab46ab4543b0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b23c8d0a22cf4a839042bfdcc68fccbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜帘宝/u0.jpg"}},
{
          "id":"4457b4a8fcfb444bb6008c2607234020",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":72},
            "size":{
              "width":250,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7cf5f5367dc94a7ca55c5a21c5c47e59",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":116},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a16e4cef717c4277bf5ad2935e634275",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":118},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a908f13ad26c4c5687c76916468ba396",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":63,
              "y":160},
            "size":{
              "width":295,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"942a602eedfb4e04955a9f717ec180aa",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":63,
              "y":205},
            "size":{
              "width":295,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"a6102ab528a248aba7e85c3dd2ba3252",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":64,
              "y":250},
            "size":{
              "width":295,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"8ebedc812f1348f892ba87f88ff7d109",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":64,
              "y":296},
            "size":{
              "width":295,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"45aba5847749463585609c1d05fc3c25",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":64,
              "y":383},
            "size":{
              "width":295,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"dc2b8c7fb68d47e5b38959016a6b1a9c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":64,
              "y":429},
            "size":{
              "width":295,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ce09355750b8413caac29acbf48f13d6",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":64,
              "y":471},
            "size":{
              "width":295,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"98733241d0544dc9bd6e9e74d58c413f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":93,
              "y":339},
            "size":{
              "width":266,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"02b9c366d0ea4d82af56de3c41eaefda",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":560},
            "size":{
              "width":69,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"f480a8d9b1004f5ab62b4270248950f7",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":620},
            "size":{
              "width":50,
              "height":47}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open index in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"66cf17c61cb84b18b0f895a030b49dd9",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":621},
            "size":{
              "width":50,
              "height":47}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 分类 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"分类.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"ac1add5e720f42379f645eee782a590f",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":164,
              "y":619},
            "size":{
              "width":50,
              "height":47}},
          "adaptiveStyles":{
}},
{
          "id":"4ef074a4aa0a45edaeacce37237d4298",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":241,
              "y":619},
            "size":{
              "width":50,
              "height":47}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 购物车 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"92217be1d29545ee82c5d7c44057a941",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":318,
              "y":620},
            "size":{
              "width":50,
              "height":47}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 登录 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "4865bcdee7bf42caad21ab46ab4543b0":{
      "scriptId":"u0"},
    "b23c8d0a22cf4a839042bfdcc68fccbf":{
      "scriptId":"u1"},
    "4457b4a8fcfb444bb6008c2607234020":{
      "scriptId":"u2"},
    "7cf5f5367dc94a7ca55c5a21c5c47e59":{
      "scriptId":"u3"},
    "a16e4cef717c4277bf5ad2935e634275":{
      "scriptId":"u4"},
    "a908f13ad26c4c5687c76916468ba396":{
      "scriptId":"u5"},
    "942a602eedfb4e04955a9f717ec180aa":{
      "scriptId":"u6"},
    "a6102ab528a248aba7e85c3dd2ba3252":{
      "scriptId":"u7"},
    "8ebedc812f1348f892ba87f88ff7d109":{
      "scriptId":"u8"},
    "45aba5847749463585609c1d05fc3c25":{
      "scriptId":"u9"},
    "dc2b8c7fb68d47e5b38959016a6b1a9c":{
      "scriptId":"u10"},
    "ce09355750b8413caac29acbf48f13d6":{
      "scriptId":"u11"},
    "98733241d0544dc9bd6e9e74d58c413f":{
      "scriptId":"u12"},
    "02b9c366d0ea4d82af56de3c41eaefda":{
      "scriptId":"u13"},
    "f480a8d9b1004f5ab62b4270248950f7":{
      "scriptId":"u14"},
    "66cf17c61cb84b18b0f895a030b49dd9":{
      "scriptId":"u15"},
    "ac1add5e720f42379f645eee782a590f":{
      "scriptId":"u16"},
    "4ef074a4aa0a45edaeacce37237d4298":{
      "scriptId":"u17"},
    "92217be1d29545ee82c5d7c44057a941":{
      "scriptId":"u18"}}});