$axure.loadCurrentPage({
  "url":"index.html",
  "generationDate":new Date(1488438989322.99),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3734a1b974834afc8e302f7962fc5466",
    "type":"Axure:Page",
    "name":"index",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6207891547114767b5937756189805f3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a30d433d0f2493fb51b123a23e960e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u0.jpg"}},
{
          "id":"a6b9c40ac728416a92e8254d85e7dd6f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":9},
            "size":{
              "width":250,
              "height":31}},
          "adaptiveStyles":{
}},
{
          "id":"08389bffa8774ea9941568237a7de621",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":214},
            "size":{
              "width":50,
              "height":71}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 预算 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"预算.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3e352592e9a04f488fdf9ed36a4a9467",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":214},
            "size":{
              "width":50,
              "height":71}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜帘宝 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜帘宝.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e567adcfb9864294ac8611b0c7bf8ba3",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":212},
            "size":{
              "width":50,
              "height":71}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 优惠速递 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"优惠速递.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"1c2b032891d84489834753d42d37eafd",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":307,
              "y":209},
            "size":{
              "width":50,
              "height":71}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 晒单 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"晒单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"bfe1ffabe89b49e8a4801e697592c995",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":308},
            "size":{
              "width":170,
              "height":253}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"692df1f5577e44ecbc7145fd8a716234",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":196,
              "y":305},
            "size":{
              "width":170,
              "height":253}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3a8d025d6e124412a67fa9ba216cbf77",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":0,
              "y":561},
            "size":{
              "width":375,
              "height":105},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"528a8ab8b9cb45b3a78a97b958d750fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":0,
                  "y":561},
                "size":{
                  "width":375,
                  "height":105},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u9.png"}},
{
          "id":"ed49e66d3312400abe8c5c945ab018c8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":580},
            "size":{
              "width":176,
              "height":253}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a919581355594a92a25260fc59ef3690",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":580},
                "size":{
                  "width":176,
                  "height":253}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u11.png"}},
{
          "id":"9bf6a3b8898c4f33bc4417ef37676b47",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":7,
              "y":580},
            "size":{
              "width":176,
              "height":253}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eed0392a93fc4e2fa232a6881e503acb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":7,
                  "y":580},
                "size":{
                  "width":176,
                  "height":253}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u13.png"}},
{
          "id":"692461f5b13544e1be20d41e5179459c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":580},
            "size":{
              "width":170,
              "height":253}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f17bac05afda4d49a19388786858912d",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":580},
            "size":{
              "width":170,
              "height":253}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"63a9571377024e8e97cb7e97ad41a73c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF8E01C},
            "location":{
              "x":0,
              "y":843},
            "size":{
              "width":375,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e2cfe8a70434dc180d182c988ef236a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF8E01C},
                "location":{
                  "x":0,
                  "y":843},
                "size":{
                  "width":375,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u17.png"}},
{
          "id":"460f96c48125478cb3e36353087c5311",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":844},
            "size":{
              "width":27,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"710537a5d0b94a76af7ae3d9e8a63bfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":23,
                  "y":844},
                "size":{
                  "width":27,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u19.png"}},
{
          "id":"c3f6048648064abeab21b89e32340b56",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":844},
            "size":{
              "width":27,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86c55c491b3543a983866c7b8df534e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":844},
                "size":{
                  "width":27,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u21.png"}},
{
          "id":"149db24484e042a3b02645cabcd3e6a7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":844},
            "size":{
              "width":27,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0e415d6078d427582043a4ec38e4fcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":253,
                  "y":844},
                "size":{
                  "width":27,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u23.png"}},
{
          "id":"a27ae861f7234fe38e27ec1641ace8d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":845},
            "size":{
              "width":27,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a277a639b4d475ca5dc4f1555652e67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":845},
                "size":{
                  "width":27,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u25.png"}},
{
          "id":"fd118fd3009f4211a29640ce29257e9d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":846},
            "size":{
              "width":27,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73e8fec177194cd4b04b235bc76f8bb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":846},
                "size":{
                  "width":27,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u27.png"}},
{
          "id":"749d2df8c50d4181a6ac1e743c69d4d1",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":845},
            "size":{
              "width":48,
              "height":44}},
          "adaptiveStyles":{
}},
{
          "id":"e2803f0f6a884be990f65cf7a36b3edd",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":159.5,
              "y":846},
            "size":{
              "width":48,
              "height":44}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 分类 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"分类.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b09d39d7f7ef4a47a87ba01e2cfe2afe",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":242.5,
              "y":844},
            "size":{
              "width":48,
              "height":44}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 购物车 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"190705be72c74b37b51faca7e0bca317",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":313.5,
              "y":845},
            "size":{
              "width":48,
              "height":44}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 登录 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "6207891547114767b5937756189805f3":{
      "scriptId":"u0"},
    "9a30d433d0f2493fb51b123a23e960e0":{
      "scriptId":"u1"},
    "a6b9c40ac728416a92e8254d85e7dd6f":{
      "scriptId":"u2"},
    "08389bffa8774ea9941568237a7de621":{
      "scriptId":"u3"},
    "3e352592e9a04f488fdf9ed36a4a9467":{
      "scriptId":"u4"},
    "e567adcfb9864294ac8611b0c7bf8ba3":{
      "scriptId":"u5"},
    "1c2b032891d84489834753d42d37eafd":{
      "scriptId":"u6"},
    "bfe1ffabe89b49e8a4801e697592c995":{
      "scriptId":"u7"},
    "692df1f5577e44ecbc7145fd8a716234":{
      "scriptId":"u8"},
    "3a8d025d6e124412a67fa9ba216cbf77":{
      "scriptId":"u9"},
    "528a8ab8b9cb45b3a78a97b958d750fe":{
      "scriptId":"u10"},
    "ed49e66d3312400abe8c5c945ab018c8":{
      "scriptId":"u11"},
    "a919581355594a92a25260fc59ef3690":{
      "scriptId":"u12"},
    "9bf6a3b8898c4f33bc4417ef37676b47":{
      "scriptId":"u13"},
    "eed0392a93fc4e2fa232a6881e503acb":{
      "scriptId":"u14"},
    "692461f5b13544e1be20d41e5179459c":{
      "scriptId":"u15"},
    "f17bac05afda4d49a19388786858912d":{
      "scriptId":"u16"},
    "63a9571377024e8e97cb7e97ad41a73c":{
      "scriptId":"u17"},
    "2e2cfe8a70434dc180d182c988ef236a":{
      "scriptId":"u18"},
    "460f96c48125478cb3e36353087c5311":{
      "scriptId":"u19"},
    "710537a5d0b94a76af7ae3d9e8a63bfa":{
      "scriptId":"u20"},
    "c3f6048648064abeab21b89e32340b56":{
      "scriptId":"u21"},
    "86c55c491b3543a983866c7b8df534e9":{
      "scriptId":"u22"},
    "149db24484e042a3b02645cabcd3e6a7":{
      "scriptId":"u23"},
    "f0e415d6078d427582043a4ec38e4fcd":{
      "scriptId":"u24"},
    "a27ae861f7234fe38e27ec1641ace8d7":{
      "scriptId":"u25"},
    "1a277a639b4d475ca5dc4f1555652e67":{
      "scriptId":"u26"},
    "fd118fd3009f4211a29640ce29257e9d":{
      "scriptId":"u27"},
    "73e8fec177194cd4b04b235bc76f8bb9":{
      "scriptId":"u28"},
    "749d2df8c50d4181a6ac1e743c69d4d1":{
      "scriptId":"u29"},
    "e2803f0f6a884be990f65cf7a36b3edd":{
      "scriptId":"u30"},
    "b09d39d7f7ef4a47a87ba01e2cfe2afe":{
      "scriptId":"u31"},
    "190705be72c74b37b51faca7e0bca317":{
      "scriptId":"u32"}}});