$axure.loadCurrentPage({
  "url":"预算.html",
  "generationDate":new Date(1488187959753.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"32f0a22193a84320a6d1fb346d9214dd",
    "type":"Axure:Page",
    "name":"预算",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"50aad2a8e715430aa6b321593d42fe66",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b766fd36a6f4ad385ce661a0ef19468",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预算/u0.jpg"}},
{
          "id":"8a1f29e81c7a44298e0613999ebd50df",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":68,
              "y":473},
            "size":{
              "width":90,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"dd1dff2040294dd39fa74db3b1d4b716",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":472},
            "size":{
              "width":90,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"fa40640ac7a04beeb805b6de367666b5",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":640},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open index in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e55ae6c0134c4bdbae27a28aada1e6c1",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":637},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open index in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "50aad2a8e715430aa6b321593d42fe66":{
      "scriptId":"u0"},
    "2b766fd36a6f4ad385ce661a0ef19468":{
      "scriptId":"u1"},
    "8a1f29e81c7a44298e0613999ebd50df":{
      "scriptId":"u2"},
    "dd1dff2040294dd39fa74db3b1d4b716":{
      "scriptId":"u3"},
    "fa40640ac7a04beeb805b6de367666b5":{
      "scriptId":"u4"},
    "e55ae6c0134c4bdbae27a28aada1e6c1":{
      "scriptId":"u5"}}});