$axure.loadCurrentPage({
  "url":"预算.html",
  "generationDate":new Date(1488438989593.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"32f0a22193a84320a6d1fb346d9214dd",
    "type":"Axure:Page",
    "name":"预算",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"50aad2a8e715430aa6b321593d42fe66",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b766fd36a6f4ad385ce661a0ef19468",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预算/u0.jpg"}},
{
          "id":"8a1f29e81c7a44298e0613999ebd50df",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":68,
              "y":473},
            "size":{
              "width":90,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"dd1dff2040294dd39fa74db3b1d4b716",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":472},
            "size":{
              "width":90,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"fa40640ac7a04beeb805b6de367666b5",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":640},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open index in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e55ae6c0134c4bdbae27a28aada1e6c1",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":637},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open index in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8696db3f9db540daab3aa1eac43e4d29",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF8E01C},
            "location":{
              "x":0,
              "y":677},
            "size":{
              "width":375,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2895930fe65648b0911b4eb35dd2e026",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF8E01C},
                "location":{
                  "x":0,
                  "y":677},
                "size":{
                  "width":375,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u17.png"}},
{
          "id":"c0bd675ae1ee4ea78acc0c4fb007b743",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":678},
            "size":{
              "width":27,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d97d8800851b4f94a945eb4f082a1667",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":23,
                  "y":678},
                "size":{
                  "width":27,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u19.png"}},
{
          "id":"ab2a2fb92b5b4b4a95e49e1976b7b916",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":678},
            "size":{
              "width":27,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b21010173800417da37df5fe06c05779",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":678},
                "size":{
                  "width":27,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u21.png"}},
{
          "id":"60a53de753be40aa8311fe428260826a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":678},
            "size":{
              "width":27,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f322f9d4a176472abf83250dc18be859",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":253,
                  "y":678},
                "size":{
                  "width":27,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u23.png"}},
{
          "id":"29242b3bc8d641efa85d066064964563",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":679},
            "size":{
              "width":27,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63d71d702f5b40548c10870830879203",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":679},
                "size":{
                  "width":27,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u25.png"}},
{
          "id":"b349218f22ea4f12875d8066a4eea703",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":680},
            "size":{
              "width":27,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2647966cfc5441e82f5ca8c4175f33f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":680},
                "size":{
                  "width":27,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u27.png"}},
{
          "id":"8a14b0e48d574137bcc7afe89fe17175",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":12.5,
              "y":678},
            "size":{
              "width":48,
              "height":44}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open index in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"d2a44d45bcc8444694793ce2e6962adc",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":680},
            "size":{
              "width":48,
              "height":44}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 分类 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"分类.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"284335bd145947d1b45c094c7e724fa4",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":242,
              "y":678},
            "size":{
              "width":48,
              "height":44}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 购物车 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9339d0f005c64816b1ebcd0a83c3b4d2",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":679},
            "size":{
              "width":48,
              "height":44}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 登录 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "50aad2a8e715430aa6b321593d42fe66":{
      "scriptId":"u0"},
    "2b766fd36a6f4ad385ce661a0ef19468":{
      "scriptId":"u1"},
    "8a1f29e81c7a44298e0613999ebd50df":{
      "scriptId":"u2"},
    "dd1dff2040294dd39fa74db3b1d4b716":{
      "scriptId":"u3"},
    "fa40640ac7a04beeb805b6de367666b5":{
      "scriptId":"u4"},
    "e55ae6c0134c4bdbae27a28aada1e6c1":{
      "scriptId":"u5"},
    "8696db3f9db540daab3aa1eac43e4d29":{
      "scriptId":"u6"},
    "2895930fe65648b0911b4eb35dd2e026":{
      "scriptId":"u7"},
    "c0bd675ae1ee4ea78acc0c4fb007b743":{
      "scriptId":"u8"},
    "d97d8800851b4f94a945eb4f082a1667":{
      "scriptId":"u9"},
    "ab2a2fb92b5b4b4a95e49e1976b7b916":{
      "scriptId":"u10"},
    "b21010173800417da37df5fe06c05779":{
      "scriptId":"u11"},
    "60a53de753be40aa8311fe428260826a":{
      "scriptId":"u12"},
    "f322f9d4a176472abf83250dc18be859":{
      "scriptId":"u13"},
    "29242b3bc8d641efa85d066064964563":{
      "scriptId":"u14"},
    "63d71d702f5b40548c10870830879203":{
      "scriptId":"u15"},
    "b349218f22ea4f12875d8066a4eea703":{
      "scriptId":"u16"},
    "d2647966cfc5441e82f5ca8c4175f33f":{
      "scriptId":"u17"},
    "8a14b0e48d574137bcc7afe89fe17175":{
      "scriptId":"u18"},
    "d2a44d45bcc8444694793ce2e6962adc":{
      "scriptId":"u19"},
    "284335bd145947d1b45c094c7e724fa4":{
      "scriptId":"u20"},
    "9339d0f005c64816b1ebcd0a83c3b4d2":{
      "scriptId":"u21"}}});