$axure.loadCurrentPage({
  "url":"分类.html",
  "generationDate":new Date(1488187959679.57),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cf8a5cea6d4d4cdca73f5e8165a24553",
    "type":"Axure:Page",
    "name":"分类",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"869e9da8432041f1b209725891dadf3b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9902c62ceb964732b7e111d82fc48a75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分类/u0.jpg"}},
{
          "id":"d5b264f3098642bd9af6591e807d4e42",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":620},
            "size":{
              "width":50,
              "height":47}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open index in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"2ef456a1da50487bb87b375aaf0c391b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":244,
              "y":622},
            "size":{
              "width":50,
              "height":47}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 购物车 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b5c26fbc004b4bde82ae609af45dfbaa",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":321,
              "y":622},
            "size":{
              "width":50,
              "height":47}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 登录 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "869e9da8432041f1b209725891dadf3b":{
      "scriptId":"u0"},
    "9902c62ceb964732b7e111d82fc48a75":{
      "scriptId":"u1"},
    "d5b264f3098642bd9af6591e807d4e42":{
      "scriptId":"u2"},
    "2ef456a1da50487bb87b375aaf0c391b":{
      "scriptId":"u3"},
    "b5c26fbc004b4bde82ae609af45dfbaa":{
      "scriptId":"u4"}}});