$axure.loadCurrentPage({
  "url":"晒单.html",
  "generationDate":new Date(1488438989443.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7d9144d12e17482ab69288197350aa0a",
    "type":"Axure:Page",
    "name":"晒单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"93ca37e59244435db4f7cc56dbb89fb2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c648c07098d14b52b24ce49c861f4b74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/晒单/u0.jpg"}},
{
          "id":"a5178acae7724e078473818edcf24441",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":40},
            "size":{
              "width":170,
              "height":260}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"73bee9fafdb441e5829025b9dbeafe7b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":195,
              "y":37},
            "size":{
              "width":170,
              "height":260}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"89063fed80734f3eaf61cca636295f68",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":308},
            "size":{
              "width":170,
              "height":260}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9afd7d66a93241f287969d77c24a4e38",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":308},
            "size":{
              "width":170,
              "height":260}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"36f3ff192c1b4a78be9273989b3d2781",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":574},
            "size":{
              "width":361,
              "height":96},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd5f3855e10946848d21f1750ddfeade",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":574},
                "size":{
                  "width":361,
                  "height":96},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/晒单/u6.png"}},
{
          "id":"69ea3ad11cfb4f0592179786eba5d1b7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":580},
            "size":{
              "width":176,
              "height":253}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d651de461b8e43fb9b1eb6d01ea78dd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":580},
                "size":{
                  "width":176,
                  "height":253}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u11.png"}},
{
          "id":"905b0115d49b4e648fafad9de5dd78ca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":7,
              "y":580},
            "size":{
              "width":176,
              "height":253}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7255ea0e1e24eca9c61133f5279a114",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":7,
                  "y":580},
                "size":{
                  "width":176,
                  "height":253}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u13.png"}},
{
          "id":"85d11132839a412891ab79dfdb5dec0b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":580},
            "size":{
              "width":170,
              "height":253}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a58a67d5cb66486cb9ef4ace91240116",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":580},
            "size":{
              "width":170,
              "height":253}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"74c0cbb106004c33932cf9d02dd07ab4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF8E01C},
            "location":{
              "x":0,
              "y":843},
            "size":{
              "width":367,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7814f29974a84e9d9de4e0b9a145feca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF8E01C},
                "location":{
                  "x":0,
                  "y":843},
                "size":{
                  "width":367,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/晒单/u14.png"}},
{
          "id":"2cdf8273795e4094ace3a04e329c992b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":844},
            "size":{
              "width":26,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"885bbe481d0c4b558169819c53db0420",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":23,
                  "y":844},
                "size":{
                  "width":26,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u19.png"}},
{
          "id":"f88d60be5aeb4464a462418b4e42333f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":844},
            "size":{
              "width":26,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71598655a15040d6857bf51ee0708d8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":84,
                  "y":844},
                "size":{
                  "width":26,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u21.png"}},
{
          "id":"20d307ec82c14dd394b7e9bcb64e8b9d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":248,
              "y":844},
            "size":{
              "width":26,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0f5f72bb491423983e913fe252d4d20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":248,
                  "y":844},
                "size":{
                  "width":26,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u23.png"}},
{
          "id":"11440c3b692742af951c287999c7011d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":317,
              "y":845},
            "size":{
              "width":26,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2a50e073a4942f5bec2ed25d5ee1108",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":317,
                  "y":845},
                "size":{
                  "width":26,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u25.png"}},
{
          "id":"6ed3faeae2034de5a5b2df84dfa28f9d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":166,
              "y":846},
            "size":{
              "width":26,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0ec6d0c9043485b9be3d3e3de233fb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":166,
                  "y":846},
                "size":{
                  "width":26,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u27.png"}},
{
          "id":"ceb414c4a9c74ed5a91dbd1fa2f73026",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":844},
            "size":{
              "width":48,
              "height":44}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open index in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"4d5d5ae4906c4b6f951229b24608a345",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":159.5,
              "y":846},
            "size":{
              "width":48,
              "height":44}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 分类 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"分类.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"96cf8cfe72644087b146a5197b213994",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":242.5,
              "y":844},
            "size":{
              "width":48,
              "height":44}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 购物车 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7c594308de0e407d83b3caa7e57ada9e",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":313.5,
              "y":845},
            "size":{
              "width":48,
              "height":44}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 登录 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "93ca37e59244435db4f7cc56dbb89fb2":{
      "scriptId":"u0"},
    "c648c07098d14b52b24ce49c861f4b74":{
      "scriptId":"u1"},
    "a5178acae7724e078473818edcf24441":{
      "scriptId":"u2"},
    "73bee9fafdb441e5829025b9dbeafe7b":{
      "scriptId":"u3"},
    "89063fed80734f3eaf61cca636295f68":{
      "scriptId":"u4"},
    "9afd7d66a93241f287969d77c24a4e38":{
      "scriptId":"u5"},
    "36f3ff192c1b4a78be9273989b3d2781":{
      "scriptId":"u6"},
    "fd5f3855e10946848d21f1750ddfeade":{
      "scriptId":"u7"},
    "69ea3ad11cfb4f0592179786eba5d1b7":{
      "scriptId":"u8"},
    "d651de461b8e43fb9b1eb6d01ea78dd0":{
      "scriptId":"u9"},
    "905b0115d49b4e648fafad9de5dd78ca":{
      "scriptId":"u10"},
    "d7255ea0e1e24eca9c61133f5279a114":{
      "scriptId":"u11"},
    "85d11132839a412891ab79dfdb5dec0b":{
      "scriptId":"u12"},
    "a58a67d5cb66486cb9ef4ace91240116":{
      "scriptId":"u13"},
    "74c0cbb106004c33932cf9d02dd07ab4":{
      "scriptId":"u14"},
    "7814f29974a84e9d9de4e0b9a145feca":{
      "scriptId":"u15"},
    "2cdf8273795e4094ace3a04e329c992b":{
      "scriptId":"u16"},
    "885bbe481d0c4b558169819c53db0420":{
      "scriptId":"u17"},
    "f88d60be5aeb4464a462418b4e42333f":{
      "scriptId":"u18"},
    "71598655a15040d6857bf51ee0708d8a":{
      "scriptId":"u19"},
    "20d307ec82c14dd394b7e9bcb64e8b9d":{
      "scriptId":"u20"},
    "b0f5f72bb491423983e913fe252d4d20":{
      "scriptId":"u21"},
    "11440c3b692742af951c287999c7011d":{
      "scriptId":"u22"},
    "f2a50e073a4942f5bec2ed25d5ee1108":{
      "scriptId":"u23"},
    "6ed3faeae2034de5a5b2df84dfa28f9d":{
      "scriptId":"u24"},
    "f0ec6d0c9043485b9be3d3e3de233fb7":{
      "scriptId":"u25"},
    "ceb414c4a9c74ed5a91dbd1fa2f73026":{
      "scriptId":"u26"},
    "4d5d5ae4906c4b6f951229b24608a345":{
      "scriptId":"u27"},
    "96cf8cfe72644087b146a5197b213994":{
      "scriptId":"u28"},
    "7c594308de0e407d83b3caa7e57ada9e":{
      "scriptId":"u29"}}});